# ================================================
# Aplicacao
# ================================================

spring.application.name=libra


# ================================================
# Banco de dados Oracle EBS
# ================================================

spring.datasource.url=${ORACLE_DB_EBS_CONNECT_STRING}
spring.datasource.username=${ORACLE_DB_EBS_USER}
spring.datasource.password=${ORACLE_DB_EBS_PWD}


# ================================================
# Pool de conexoes Oracle UCP
# ================================================

spring.datasource.type=oracle.ucp.jdbc.PoolDataSourceImpl
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.connection-pool-name=LibraUcpOracle
spring.datasource.oracleucp.initial-pool-size=5
spring.datasource.oracleucp.min-pool-size=5
spring.datasource.oracleucp.max-pool-size=20
spring.datasource.oracleucp.connection-wait-duration=10s

# ================================================
# Certificado SSL
# ================================================

server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/api-certificate.p12
server.ssl.key-store-password=${API_CERT_PWD}

# ================================================
# Seguranca da API
# ================================================

http.auth-token-header-name=x-api-key
http.auth-token=${API_KEY}

# ================================================
# Monitoramento local
# ================================================

#management.endpoint.health.show-details=always