-- Aplicar procedimento no ambiente Oracle EBS:

-- Criação do profile de banco de dados para limitações de acesso:

CREATE PROFILE "XCXP_SGV_PF" LIMIT CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME DEFAULT
SESSIONS_PER_USER 100
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 335
PASSWORD_GRACE_TIME 30
PASSWORD_REUSE_MAX 12
PASSWORD_REUSE_TIME 365
PASSWORD_LOCK_TIME DEFAULT
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_VERIFY_FUNCTION DEFAULT;

-- Incluir a profile na função de complexidade de senhas (Utilizar o SQL Plus, caso não funcionar pelo PL SQL Developer):
ALTER PROFILE "XCXP_SGV_PF" LIMIT PASSWORD_VERIFY_FUNCTION XCXP_PASSWORD_STRONG_VERIFY_FUNCTION;

-- Criação do tablespace para o usuário:
-- EXADATA: Alterar o datafile conforme ambiente (DEV -> +DATADEV / HO -> +DATAHOM / PRD -> +DATAPRD / DR -> +DATADRE):
-- SUPER CLUSTER: Alterar o datafile conforme ambiente (DEV -> +DATA_DEV / HO -> +DATA_HO / PRD -> +DATA_PRD / DR -> +DATA_DR):

CREATE TABLESPACE XXSGVD
    DATAFILE '+DATADEV' SIZE 1000M;
	
CREATE TABLESPACE XXSGVX
    DATAFILE '+DATADEV' SIZE 1000M;

-- Criação do usuário XXSGV (Conexão STARK-API com EBS)
-- Definir a senha conforme ambiente (DEV, HO e PRD)

CREATE USER XXSGV PROFILE "XCXP_SGV_PF"
    IDENTIFIED BY "xxxxxxxxxxxxxxxxx" DEFAULT TABLESPACE XXSGVD
    ACCOUNT UNLOCK;

ALTER USER XXSGV QUOTA UNLIMITED ON XXSGVD;
ALTER USER XXSGV ENABLE EDITIONS;

-- Concessão dos grants para o usuário XXSGV:
GRANT CONNECT TO XXSGV;
GRANT CREATE SYNONYM TO XXSGV;
